### ISSUE TITLE
integer conversion thoughts

### ISSUE THREAD

**Issue by seaaan** [ropenscilabs/umapr#20]
Some arguments are converted to integers with `as.integer` if the Python code expects an integer, allowing R users to supply, e.g., `1` instead of `1L`. However, if the user supplies, e.g, `1.5`, this will be converted to `1L`, where it might be more appropriate to throw an error.

**Comment by laderast** [comment]
Maybe a test for size of `data.frame`, should be less than 1/2 of available memory?

**Comment by angela-li** [comment]
Closed in #21
