### ISSUE TITLE
add note saying umapr is unconf18 project?

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/umapr#24]
I think it would be helpful to indicate near top of README that umapr is/was an unconf18 project (with all that implies e.g. exploration). Given existence of [`umap`](https://github.com/tkonopka/umap) by [Tomasz Konopka](https://github.com/tkonopka/) (which I know you linked to 👍) under current development, it would be good to be clear about this so that others don't perceive you're about to race to CRAN as is, for example.

**Comment by laderast** [comment]
Readme is now updated @stefaniebutland . Thanks for pointing this out
