### ISSUE TITLE
n_component ==1 

### ISSUE THREAD

**Issue by GalliES** [ropenscilabs/umapr#28]
Hi, I am trying to use the package to create a UMAP-based unicategorical analysis (similar to ONEsense), but when I change:

umap.defaults$n_component == 1, 

i get an error after the algorithm tries to create the initial embedding:

(Error in result[, 1:d, drop = FALSE] : incorrect number of dimensions) 

I think that for the Python version this works fine. Am I doing something wrong? Can you help me out?

Thx

Ed

**Comment by seaaan** [comment]
Can you post more of your code? The call should be something like `umap(<data>, n_components = 1)`. I can't tell from your post what you're doing. You shouldn't need to use `$` I don't think.

I'd also suggest you to look into using a different UMAP package in R, which provide more features than `umapr` does and are more actively developed. These packages are:

-   [umap](https://github.com/tkonopka/umap), which provides the same Python wrapping function as `umapr` and also an R implementation, removing the need for the Python version to be installed. It is available on [CRAN](https://cran.r-project.org/web/packages/umap/index.html).

-   [uwot](https://github.com/jlmelville/uwot), which also provides an R implementation, removing the need for the Python version to be installed.
