### ISSUE TITLE
testing error : TypeError: __init__() got an unexpected keyword argument 'bandwidth'

### ISSUE THREAD

**Issue by aelkhouly85** [ropenscilabs/umapr#29]
after successful install , I still can not get it running , I'm always getting this error while testing.
> embedding <- umap(df)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
"TypeError: __init__() got an unexpected keyword argument 'bandwidth'"  
Any idea how to resolve this issue?

**Comment by seaaan** [comment]
I suggest you try using one of these two other UMAP R packages, which provide more features than `umapr` does and are more actively developed. These packages are:

-   [umap](https://github.com/tkonopka/umap), which provides the same Python wrapping function as `umapr` and also an R implementation, removing the need for the Python version to be installed. It is available on [CRAN](https://cran.r-project.org/web/packages/umap/index.html).

-   [uwot](https://github.com/jlmelville/uwot), which also provides an R implementation, removing the need for the Python version to be installed.
