### ISSUE TITLE
Transfer to personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/umapr#33]
@seaaan et al :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by seaaan** [comment]
Hi Maëlle! Nice to hear from you. I think that the archive option makes the
most sense. Since the unconf, several other packages have emerged that
provide the same or better functionality and are better maintained. So,
we're not really updating this package. Thanks for getting in touch!

**Comment by maelle** [comment]
Thanks @seaaan for your quick answer! :pray: I'll transfer the repo then. Thanks again!
